export const THEMES = {
  'midnight-indigo': {
    sidebarBg: 'bg-[#1b1c28]',
    sidebarHeader: 'bg-[#1b1c28]',
    sidebarText: 'text-slate-300',
    sidebarHover: 'hover:bg-[#2d3042]',
    sidebarActive: 'bg-[#3b3e54] text-white',
    sidebarBorder: 'border-[#101019]',
    listBg: 'bg-[#f9f9fb]',
    listHeader: 'bg-[#f9f9fb]',
    listText: 'text-slate-700',
    listHover: 'hover:bg-[#f8f9fa]',
    listActive: 'bg-[#eef2f9]',
    listBorder: 'border-slate-200',
    editorBg: 'bg-white',
    editorHeader: 'bg-[#1b1c28]',
    editorText: 'text-slate-800',
    editorBorder: 'border-slate-200',
    dropdownBg: 'bg-white',
    dropdownText: 'text-slate-800',
    prose: 'prose',
    codeTheme: 'light'
  },
  'cloud-nine': {
    sidebarBg: 'bg-[#f4f4f7]',
    sidebarHeader: 'bg-[#f4f4f7]',
    sidebarText: 'text-slate-600',
    sidebarHover: 'hover:bg-[#e4e4e9]',
    sidebarActive: 'bg-white text-slate-900 shadow-sm',
    sidebarBorder: 'border-slate-200',
    listBg: 'bg-white',
    listHeader: 'bg-white',
    listText: 'text-slate-700',
    listHover: 'hover:bg-[#f8f9fa]',
    listActive: 'bg-[#eef2f9]',
    listBorder: 'border-slate-200',
    editorBg: 'bg-white',
    editorHeader: 'bg-[#f4f4f7]',
    editorText: 'text-slate-800',
    editorBorder: 'border-slate-200',
    dropdownBg: 'bg-white',
    dropdownText: 'text-slate-800',
    prose: 'prose',
    codeTheme: 'light'
  },
  'arctic-night': {
    sidebarBg: 'bg-[#eceff4]',
    sidebarHeader: 'bg-[#eceff4]',
    sidebarText: 'text-[#4c566a]',
    sidebarHover: 'hover:bg-[#e5e9f0]',
    sidebarActive: 'bg-[#d8dee9] text-[#2e3440]',
    sidebarBorder: 'border-[#d8dee9]',
    listBg: 'bg-[#434c5e]',
    listHeader: 'bg-[#434c5e]',
    listText: 'text-[#eceff4]',
    listHover: 'hover:bg-[#4c566a]',
    listActive: 'bg-[#3b4252]',
    listBorder: 'border-[#3b4252]',
    editorBg: 'bg-[#2e3440]',
    editorHeader: 'bg-[#eceff4]',
    editorText: 'text-[#eceff4]',
    editorBorder: 'border-[#3b4252]',
    dropdownBg: 'bg-[#3b4252]',
    dropdownText: 'text-[#eceff4]',
    prose: 'prose prose-invert prose-p:text-[#e5e9f0] prose-h1:text-white',
    codeTheme: 'dark'
  },
  'cyber-ronin': {
    sidebarBg: 'bg-[#1e2329]',
    sidebarHeader: 'bg-[#171b1f]',
    sidebarText: 'text-[#8892b0]',
    sidebarHover: 'hover:bg-[#252b33]',
    sidebarActive: 'bg-[#2b303b] text-[#58a6ff]',
    sidebarBorder: 'border-[#171b1f]',
    listBg: 'bg-[#252b33]',
    listHeader: 'bg-[#1e2329]',
    listText: 'text-[#c9d1d9]',
    listHover: 'hover:bg-[#2b303b]',
    listActive: 'bg-[#343a45]',
    listBorder: 'border-[#1e2329]',
    editorBg: 'bg-[#15191e]',
    editorHeader: 'bg-[#1e2329]',
    editorText: 'text-[#c9d1d9]',
    editorBorder: 'border-[#252b33]',
    dropdownBg: 'bg-[#1e2329]',
    dropdownText: 'text-[#c9d1d9]',
    prose: 'prose prose-invert prose-p:text-[#8b9eb5] prose-h1:text-[#64ffda] prose-a:text-[#58a6ff]',
    codeTheme: 'dark'
  },
  'custom': {
    sidebarBg: 'bg-[var(--custom-sidebar-bg)]',
    sidebarHeader: 'bg-[var(--custom-sidebar-header)]',
    sidebarText: 'text-[var(--custom-sidebar-text)]',
    sidebarHover: 'hover:bg-white/5',
    sidebarActive: 'bg-white/10 text-white shadow-lg',
    sidebarBorder: 'border-white/10',
    listBg: 'bg-[var(--custom-list-bg)]',
    listHeader: 'bg-[var(--custom-list-header)]',
    listText: 'text-[var(--custom-list-text)]',
    listHover: 'hover:bg-black/10',
    listActive: 'bg-white/10',
    listBorder: 'border-white/10',
    editorBg: 'bg-[var(--custom-editor-bg)]',
    editorHeader: 'bg-[var(--custom-editor-header)]',
    editorText: 'text-[var(--custom-editor-text)]',
    editorBorder: 'border-white/10',
    dropdownBg: 'bg-slate-800',
    dropdownText: 'text-white',
    prose: 'prose prose-invert',
    codeTheme: 'dark'
  }
};
